### ISSUE TITLE
Can I enable CORS via docker ? 

### ISSUE THREAD

**Issue by lenchik-ponchik** [swagger-mock/swagger-mock#16]
What am I supposed to do to make it work?
Should I use nginx with proxy ?

**Comment by strider2038** [comment]
@lenchik-ponchik the best way is to add this feature into application. I will try to add this as soon as I have a free time.

**Comment by lenchik-ponchik** [comment]
@strider2038 Thanks. Anyway, I implemented this with nginx and docker already.
