### ISSUE TITLE
servers not taken into account

### ISSUE THREAD

**Issue by petitout** [swagger-mock/swagger-mock#22]
I have a definition which includes :

```
servers:
  - url: /my/base/path

```

and let say this api defined :

```
paths:
  /myapi:
    get: ...
```

swagger-mock serves correctly http://localhost:8080/myapi but returns a 404 error when I try to request http://localhost:8080/my/base/path/myapi

**Comment by strider2038** [comment]
@petitout thank you for the issue! Please, check new version [v0.1.10](https://github.com/swagger-mock/swagger-mock/releases/tag/v0.1.10)
