### ISSUE TITLE
API endpoint not found.

### ISSUE THREAD

**Issue by rafaltrojanowski** [swagger-mock/swagger-mock#33]
Hi,

Followed https://github.com/swagger-mock/swagger-mock#how-to-use with remote file (Docker container) and I'm hitting `INFO[0014] 172.17.0.1 {259ms} 404 GET http://localhost:8080/pets` but there is no response. What am I doing wrong?

**Comment by strider2038** [comment]
Hello! This is because swagger mock uses server urls for routing. Valid request is `GET http://localhost:8080/v1/pets`.

**Comment by rafaltrojanowski** [comment]
Thanks for quick feedback, I've tried `api/pets`. Closing then.
