### ISSUE TITLE
Don't crash on invalid formats

### ISSUE THREAD

**Issue by bojanz** [swagger-mock/swagger-mock#63]
Right now if the spec has an unrecognized format, "serve" will fail:
```
validating OpenAPI failed: invalid components: unsupported 'format' value "ulid"
```
OpenAPI considers the format to be freeform, a hint to clients, so we can afford to be less strict.

Kin has an option for this, so all it would take is to do:
```
	openapi3.SchemaFormatValidationDisabled = true
```
somewhere before openapi3.NewLoader().

**Comment by strider2038** [comment]
Fixed in [v0.3.2](https://github.com/muonsoft/openapi-mock/releases/tag/v0.3.2)
