### ISSUE TITLE
Can't rebuild and run

### ISSUE THREAD

**Issue by lukasvopelka** [swagger-mock/swagger-mock#9]
Hello after pulling the repository and building docker file I got some fatal error during startup:

Commands:
- Pull the repo
- Make tiny change in the code
- Docker build and tag
- Docker run

Error during container startup:

Attaching to swagger_mock_fortuna
swagger_mock_fortuna | 
swagger_mock_fortuna | Fatal error: During class fetch: Uncaught ReflectionException: Class Doctrine\Common\Cache\CacheProvider not found in /app/vendor/symfony/cache/DoctrineProvider.php:21
swagger_mock_fortuna | Stack trace:
swagger_mock_fortuna | #0 /app/vendor/composer/ClassLoader.php(444): include('/app/vendor/sym...')
swagger_mock_fortuna | #1 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/app/vendor/com...')
swagger_mock_fortuna | #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
swagger_mock_fortuna | #3 [internal function]: spl_autoload_call('Symfony\\Compone...')
swagger_mock_fortuna | #4 /app/vendor/symfony/config/Resource/ClassExistenceResource.php(76): class_exists('Symfony\\Compone...')
swagger_mock_fortuna | #5 /app/vendor/symfony/dependency-injection/ContainerBuilder.php(351): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
swagger_mock_fortuna | #6 /app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(330): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Symfony\\Compone...', false)
swagger_mock_fortuna | #7 /app/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(316): Symfony\Component\Depende in /app/vendor/symfony/cache/DoctrineProvider.php on line 21
swagger_mock_fortuna exited with code 1

**Comment by gschafra** [comment]
Also got this issue with image build with given travis configuration and published to docker (see https://hub.docker.com/r/gschafra/swagger-mock)

**Comment by strider2038** [comment]
This is a strange bug. Somehow there was a missing dependency. I updated all project dependencies. @lukasvopelka can you reproduce this issue with latest version?

**Comment by lukasvopelka** [comment]
Working now.. thanks for quick fix..

**Comment by gschafra** [comment]
Confirmed... last release v1.6 is also working for me. Thanks a lot!
